"use strict";
exports.__esModule = true;
var Movie_1 = require("./Movie");
var Professional_1 = require("./Professional");
var IMDB_1 = require("./IMDB");
var actor1 = new Professional_1.Professional('Robert Downey Jr.', 55, 'Hombre', 73, 164, 'Castaño', 'Marron', 'Blanco', false, 'Estadounidense', 0, 'Actor');
var actor2 = new Professional_1.Professional('Samuel L. Jackson', 71, 'Hombre', 91, 189, 'Calvo', 'Marron', 'Negro', false, 'Estadounidense', 1, 'Actor');
var director = new Professional_1.Professional('Jon Favreau', 54, 'Hombre', 96, 176, 'Moreno', 'Marron', 'Blanco', false, 'Estadounidense', 0, 'Director');
var guionista = new Professional_1.Professional('Justin Theroux', 49, 'Hombre', 54, 171, 'Negro', 'Verdes', 'Blanco', false, 'Estadounidense', 0, 'Guionista');
var productor = new Professional_1.Professional('Kevin Feige', 47, 'Hombre', 92, 180, 'Moreno', 'Azul', 'Blanco', false, 'Estadounidense', 0, 'Productor');
var pelicula1 = new Movie_1.Movie('Iron Man 2', 2010, "America", "Accion Superheroes");
pelicula1.actors = [actor1, actor2];
pelicula1.director = director;
pelicula1.writer = guionista;
pelicula1.language = "Multilanguage";
pelicula1.plataform = "Disney Plus";
pelicula1.isMCU = true;
pelicula1.mainCharacterName = "Iron Man";
pelicula1.producer = productor;
pelicula1.distributor = "Paramount Pictures";
var actor11 = new Professional_1.Professional('Matthew McConaughey', 50, 'Hombre', 77, 182, 'Castaño', 'Marron', 'Blanco', false, 'Estadounidense', 1, 'Actor');
var actor22 = new Professional_1.Professional('Anne Hathaway', 37, 'Mujer', 56, 170, 'Castano', 'Marron', 'Blanca', false, 'Estadounidense', 1, 'Actriz');
var director2 = new Professional_1.Professional('Christopher Nolan', 50, 'Hombre', 96, 176, 'Moreno', 'Marron', 'Blanco', false, 'Britanico', 0, 'Director');
var guionista2 = new Professional_1.Professional('Jonathan Nolan', 44, 'Hombre', 54, 180, 'Negro', 'Azules', 'Blanco', false, 'Britanico', 0, 'Guionista');
var productor2 = new Professional_1.Professional('Emma Thomas', 48, 'Mujer', 70, 168, 'Moreno', 'Marron', 'Blanca', false, 'Britanica', 0, 'Productora');
var pelicula2 = new Movie_1.Movie('Interstellar', 2014, "America", "Ciencia Ficcion");
pelicula1.actors = [actor11, actor22];
pelicula1.director = director2;
pelicula1.writer = guionista2;
pelicula1.language = "Multilanguage";
pelicula1.plataform = "Netflix";
pelicula1.isMCU = false;
pelicula1.mainCharacterName = "Joseph Cooper";
pelicula1.producer = productor2;
pelicula1.distributor = "Paramount Pictures";
//actor1.mostrarTodo();
//actor2.mostrarTodo();
//director.mostrarTodo();
//guionista.mostrarTodo();
//productor.mostrarTodo();
//pelicula2.mostrar();
var bdd = new IMDB_1.IMDB([pelicula1, pelicula2]);
bdd.mostrarTodo();
